language: bash
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
  matrix:
  - secure: hr1OmY2JgPKfoTHnrLak6WQRpKR4eCXiWoz6oDLltUEbJR0YbwRL8fIHMpe8hCpJpt3q/j3BoR1qsre2JXtwuhLCBcQ7A2AZ33UAsNXilFOODbPwN1yb4qKdqqhoInT6sE9b2pNS2j9CRHhnf81GTw9u8W5sr3jP2G4TiusNMlnqct/bBobwgO/9Zsxn5pJusfb+vt7FFuSNw9obnU4tZK2sDZzr3LqUlEKH0jtwZ5vXm9sWJ7X+nKQIWYLui/c80Zw+Q5NHB7WND7DKi7PgTcGVqYJm0ATf5JnK4Zove4P6JkF03cy6nmc7Fh1x6a7so6TbT9rUEinOrq1XIYQXqHLZ/kv2jQDh6Eov42aoXlr3qtN3NfrnWXasveCtggNO/7hiPOAIJ+8hgCz813LMZwJdPt8mfYn/dCoaHMGVtadCx08i4h6/fymXYH3e0Eo8CMJV0/TQ9CmSW2cHPiZSjtuSXo/Q3eWKsOoEoMfrxczJGndw7ZbdqvNhQl5PzXC875rxwUgEKxOVap0WGitQ3dqYpWAyCGoos7LarKF0q56bz9nWBMrjtqjN3BmgtCScHURFcNM9/m5Ge73pnMgfd7sgvBfJH7IBOlJKEi0aWs8lDXTz23vMKyj1MHEhr4dqGb0NvFYeBkDJz3c0c6HtxeczvSPdg7DPBXK4bvfvfNU=
  - secure: MnLl4lHHSBRX5810iV5WB2MbLxGDcBGMuCBvtLwnHZ2X9JcwxHV0UPLQYYSx9sTIIi75vM7qd5LpCbu1/U0+k2R7vAdSZF42Mkc//od0HpU/PmKj+pB27t3IfOtH+/nWVb9NLgHnfTkuLxpu+Q6OxD31wH+Nw8gGaE5KuVBWCZxgeCTphaT6O/D4O4kqqGf8af2OC9NbInLw6vd4nrbmvkHJUcdIrEOuvIQ5fCOJ3vlEmZOI2C3J/B6OZH3pg8Ka36zRuMIfj1aBC7h+dT9DYmWvm1iy0li6c60vDLwUll1cvlCqO9yJZ+4Iff2cKKm22C3srakWauRL2UHOEtfdodGc0RDogyOBFfsImRn+0PjLH5kUAQ6Zlhb08bZWiNZg0TNM2g7mXz/X+fHfDUO6jne5P7q7CyeJuy86H+ccizTBoJYHJy4PNZnMY4267g1df5DHVsUdSRPf7UnEjGkA1cmJ8K/QkunDzi4xioVL37heOR5WDFCnp7i7izsH9GqAOXgTh1Ru0Vby8QtqQx2lLPirU//RAmrc22ngoie8VOx9szBD5HZ9+A4mh/7PHmEL24tSmmOBrPHmriG4BP/cXwIXfp5Xc8NIrBqromoToDcn1kjx8jPrU21YIBgyaSbQD96UaktDBePIKA35FxNrGd3RDVcnYNnUadTcD5CFwB8=
install:
- export REPO=$DOCKER_USER/orion
- docker build -f Dockerfile -t $REPO:$COMMIT .
script:
- docker images | grep -q $REPO
- docker run $REPO:$COMMIT | grep $(grep "ENV VERSION" Dockerfile | cut -d'=' -f2)
deploy:
- provider: script
  script: chmod +x ./push_to_docker_hub.sh && ./push_to_docker_hub.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
